### ISSUE TITLE
"inputbox.html" uses CSS zoom incorrectly

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/htmldialog-inputbox#1]
### "inputbox.html" uses CSS zoom incorrectly

In the style element of the file ...
```css
    /* Applying a global zoom to scale down the default size of Bootstrap. */
    html { zoom: 0.8; }
```

**`zoom`** does **not** work outside an **`@viewport`** at-rule. _**It is ignored according to the docs**_.

**Ref:** https://developer.mozilla.org/en-US/docs/Web/CSS/@viewport

----

### **EDIT:** (2018-08-31) 

After further tests, neither `zoom` nor `-ms-zoom` works, outside of a `@viewport` rule, in `UI::WebDialog` on **MS Windows** which runs in a MSIE WebBrowser Control.

 It **DOES** work in Chromium dialogs, outside of a `@viewport` rule, which is used by the `UI::HtmlDialog` class on SU2017 or higher. (This example is only written to use the new `UI::HtmlDialog` class, so the lack of `zoom` working in a `UI::WebDialog` may not be considered a bug for this example.)

Also tested the following in a MSIE `UI::WebDialog` and it also does NOT work.
```css
@viewport {
  -ms-min-width: auto;
  -ms-max-width: none;
  -ms-zoom: 0.75;
  -ms-user-zoom: fixed;
}
```
